#!/usr/bin/env bash
#
# install_agent.sh — render + load the launchd backup agent.
#
# Replaces the V1 `sed __HOME__` template flow with a script that:
#   1. Reads MANIFEST.txt and $TRUESIGHT_WORKSPACE
#   2. Generates <WatchPaths> from the manifest (workspace + home parents)
#   3. Renders the plist to ~/Library/LaunchAgents/me.truesight.credential-backup.plist
#   4. launchctl unload (if previously loaded) + load -w
#   5. Confirms the agent shows up in `launchctl list`
#
# Re-run this whenever MANIFEST.txt or $TRUESIGHT_WORKSPACE changes.
#
# Usage:
#   install_agent.sh                  # render + load
#   install_agent.sh --print-only     # render to stdout for inspection, don't install
#   install_agent.sh --uninstall      # unload + remove the plist

set -euo pipefail

# Auto-detect this script's repo location so credential_vault can be cloned
# anywhere (not just ~/Applications/credential_vault).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST="$REPO_DIR/MANIFEST.txt"
BACKUP_SH="$SCRIPT_DIR/backup.sh"

WORKSPACE="${TRUESIGHT_WORKSPACE:-$HOME/Applications}"
PLIST_DST="$HOME/Library/LaunchAgents/me.truesight.credential-backup.plist"
LABEL="me.truesight.credential-backup"

PRINT_ONLY=0
UNINSTALL=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --print-only) PRINT_ONLY=1 ;;
    --uninstall)  UNINSTALL=1 ;;
    -h|--help)    sed -n '3,20p' "$0"; exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
  shift
done

log() { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }

if (( UNINSTALL )); then
  log "Unloading + removing $LABEL"
  launchctl unload "$PLIST_DST" 2>/dev/null || true
  rm -f "$PLIST_DST"
  log "Done."
  exit 0
fi

[[ -f "$MANIFEST" ]] || { log "ERROR: $MANIFEST not found"; exit 1; }
[[ -x "$BACKUP_SH" ]] || { log "ERROR: $BACKUP_SH not executable"; exit 1; }

# ─── Build WatchPaths from manifest ────────────────────────────────────
# Strategy: take each manifest entry, resolve its absolute path, and add
# either the file OR its parent dir to WatchPaths. For directory entries
# (manifest paths ending in /) watch the dir itself. For file entries
# watch the file. launchd fires the agent whenever any watched path
# changes mtime.
WATCH=()

while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line%$'\r'}"
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line%"${line##*[![:space:]]}"}"
  [[ -z "$line" || "$line" =~ ^# ]] && continue

  if [[ "$line" == '${WORKSPACE}'/* ]]; then
    rel="${line#'${WORKSPACE}'/}"
    full="$WORKSPACE/${rel%/}"
  elif [[ "$line" == '~/'* ]]; then
    rel="${line#'~/'}"
    full="$HOME/${rel%/}"
  else
    continue
  fi
  # Add path if it exists. (launchd happily watches non-existent paths
  # too — it fires when they're created — but adding only existing paths
  # keeps the plist clean.)
  if [[ -e "$full" ]]; then
    WATCH+=("$full")
  fi
done < "$MANIFEST"

if (( ${#WATCH[@]} == 0 )); then
  log "ERROR: zero existing watch paths derived from $MANIFEST"
  exit 1
fi

# ─── Render plist ──────────────────────────────────────────────────────
render_plist() {
  cat <<HEADER
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Generated by credential_vault/scripts/install_agent.sh — do not edit by hand.
  To regenerate (after MANIFEST.txt or TRUESIGHT_WORKSPACE changes), run:
    $HOME/Applications/credential_vault/scripts/install_agent.sh
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$BACKUP_SH</string>
    </array>

    <key>WatchPaths</key>
    <array>
HEADER

  for w in "${WATCH[@]}"; do
    printf '        <string>%s</string>\n' "$w"
  done

  cat <<FOOTER
    </array>

    <key>ThrottleInterval</key>
    <integer>120</integer>

    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>    <integer>3</integer>
        <key>Minute</key>  <integer>0</integer>
    </dict>

    <key>RunAtLoad</key>
    <false/>

    <key>StandardOutPath</key>
    <string>/tmp/credential_vault_backup.log</string>

    <key>StandardErrorPath</key>
    <string>/tmp/credential_vault_backup.err</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
        <string>$HOME</string>
        <key>TRUESIGHT_WORKSPACE</key>
        <string>$WORKSPACE</string>
    </dict>
</dict>
</plist>
FOOTER
}

if (( PRINT_ONLY )); then
  render_plist
  exit 0
fi

log "Rendering plist → $PLIST_DST"
log "  WatchPaths: ${#WATCH[@]} entries"
log "  TRUESIGHT_WORKSPACE: $WORKSPACE"

# Unload any previously-loaded version so changes take effect.
if launchctl list | grep -q "$LABEL"; then
  log "Unloading existing agent"
  launchctl unload "$PLIST_DST" 2>/dev/null || true
fi

mkdir -p "$(dirname "$PLIST_DST")"
render_plist > "$PLIST_DST"

log "Loading agent"
launchctl load -w "$PLIST_DST"

if launchctl list | grep -q "$LABEL"; then
  log "Loaded — agent is now watching ${#WATCH[@]} paths"
else
  log "ERROR: agent did not load. Check launchctl error output."
  exit 1
fi

log "Done."
